name: Run Lint Test

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 18
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '18'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Execute Gradle command - lintDebug
      run: ./gradlew lintDevDebug

    - name: Upload Lint Report
      uses: actions/upload-artifact@v4
      with:
        name: lint-results-debug.html
        path: composeApp/build/reports/