name: Run ComposeApp Unit Test

on:
  workflow_call:

jobs:
  test:
    name: ComposeApp Unit Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

      # Run Tests Build
    - name: Run tests
      run: ./gradlew :composeApp:testDevDebugUnitTest